sudo: false

language: bash

os:
  - linux

before_script:
  - wget http://downloads.arduino.cc/arduino-1.8.4-linux64.tar.xz
  - tar xf arduino-1.8.4-linux64.tar.xz
  - mv arduino-1.8.4 $HOME/arduino_ide
  - cd $HOME/arduino_ide/hardware
  - mkdir esp8266com
  - cd esp8266com
  - git clone https://github.com/esp8266/Arduino.git esp8266
  - cd esp8266
  - git checkout 2.4.0
  - cd tools
  - python get.py
  

script:
  - cd $TRAVIS_BUILD_DIR
  - source command.sh
  - export PATH="$HOME/arduino_ide:$PATH"
  - rm -f $HOME/.arduino15/preferences.txt
  - arduino --board esp8266com:esp8266:generic:CpuFrequency=160,FlashSize=4M3M,FlashMode=dio,FlashFreq=40,LwIPVariant=v2mss536,Debug=Disabled --save-prefs
  - arduino --get-pref sketchbook.path
  - build_sketch esp3d/esp3d.ino
  
notifications:
  email:
    on_success: change
    on_failure: change
